In [4]:
import numpy as np

In [55]:
row=30
col=30
IN=np.random.randint(2, size=(row,col))

In [56]:
OUT=np.random.randint(1, size=(row,col))

In [57]:
for i in range(row):
    for j in range(col):
        if i==0 or j==0 or i==row-1 or j==col-1:
            OUT[i][j]=IN[i][j]
        else:
            if IN[i][j]==0:
                OUT[i][j]==0
            else:
                if IN[i-1][j]==0 or IN[i+1][j]==0 or IN[i][j-1]==0 or IN[i][j+1]==0:
                    OUT[i][j]=1
                else:
                    OUT[i][j]=0
                

In [58]:
print IN

[[0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0]
 [1 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 0 1]
 [0 0 0 1 0 1 1 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 0 1 0 0]
 [1 1 0 1 0 0 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 1 1]
 [0 0 0 1 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 0]
 [0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 1]
 [1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 1 0]
 [0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0]
 [1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 1]
 [1 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 0 0]
 [0 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1]
 [0 1 0 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 1

In [59]:
print OUT

[[0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0]
 [1 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 0 1]
 [0 0 0 1 0 1 1 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 0 1 0 0]
 [1 1 0 1 0 0 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 1 1]
 [0 0 0 1 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0]
 [0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 1]
 [1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 1 0]
 [0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0]
 [1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 1]
 [1 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0]
 [0 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 0 1]
 [0 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 1